server:
  port: 8085
  
spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://106.14.5.63:3306/fsd2020?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mysql
    password: 594Caoyizheng!
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false 
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
 
#指定myBatis的核心配置文件与Mapper映射文件
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.fsd2020.data
  
